
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `pgm`=list(
        `type`="software", 
        `author`="Pessina, A. L. R.; Garcia Neto, M.", 
        `year`=2025, 
        `title`="PGM: Practical Growth Modeling", 
        `publisher`="(Version 0.1.3) [jamovi module]. DOI available on https://github.com/apessina/jamovi-PGM", 
        `url`="https://github.com/apessina/jamovi-PGM"), 
    `richards`=list(
        `type`="article", 
        `author`="Tj\u00F8rve, E.; Tj\u00F8rve, K. M. C.", 
        `year`=2010, 
        `title`="A unified approach to the Richards-model family for use in growth analyses: why we need only two model forms", 
        `publisher`="Journal of Theoretical Biology", 
        `volume`=267, 
        `pages`="417\u2013425"), 
    `nlm`=list(
        `type`="software", 
        `author`="Elzhov, T. M.; Mullen, K. M.; Spiess, A.-N.; Bolker B.", 
        `year`=2023, 
        `title`="minpack.lm: R Interface to the Levenberg-Marquardt Nonlinear Least-Squares Algorithm Found in MINPACK, Plus Support for Bounds", 
        `publisher`="(Version 1.2-4) [R package]. Retrieved from https://cran.r-project.org/web/packages/minpack.lm/index.html", 
        `url`="https://cran.r-project.org/web/packages/minpack.lm/index.html"))
