
# This file is automatically generated, you probably don't want to edit this

gcurveOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "gcurveOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            deps = NULL,
            time = NULL,
            iid = NULL,
            eqHtmls = FALSE,
            parTables = TRUE,
            estTables = FALSE,
            modeling = list(),
            duplicateSetup = FALSE,
            removeSetup = FALSE,
            gofMetrics = NULL,
            errorMetrics = NULL,
            iPoints = FALSE,
            lagPoints = NULL,
            thValue = 0.01,
            ogfPoints = NULL,
            accPoints = NULL,
            asyPoints = NULL,
            aucFunction = NULL,
            aucInterval = FALSE,
            aucLower = 0,
            aucUpper = 0,
            growthPlots = FALSE,
            growthCurveColor = "red",
            growthRightAxis = FALSE,
            growthRightAxisFunc = "growthRate",
            growthRightAxisLine = "dashed",
            growthRightAxisColor = "black",
            growthNoAxis = FALSE,
            growthNoAxisFunc = "ogf",
            growthNoAxisLine = "solid",
            growthNoAxisColor = "darkgreen",
            residualPlots = FALSE,
            growthComparisonPlots = FALSE,
            comparisonRightFunc = "none",
            plotsElements = NULL,
            timeAxisFactor = 20, ...) {

            super$initialize(
                package="PGM",
                name="gcurve",
                requiresData=TRUE,
                ...)

            private$..deps <- jmvcore::OptionVariables$new(
                "deps",
                deps,
                required=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..time <- jmvcore::OptionVariable$new(
                "time",
                time,
                required=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..iid <- jmvcore::OptionVariable$new(
                "iid",
                iid,
                required=FALSE,
                rejectUnusedLevels=TRUE,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..eqHtmls <- jmvcore::OptionBool$new(
                "eqHtmls",
                eqHtmls,
                default=FALSE)
            private$..parTables <- jmvcore::OptionBool$new(
                "parTables",
                parTables,
                default=TRUE)
            private$..estTables <- jmvcore::OptionBool$new(
                "estTables",
                estTables,
                default=FALSE)
            private$..modeling <- jmvcore::OptionArray$new(
                "modeling",
                modeling,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "modeling",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "setupId",
                            NULL),
                        jmvcore::OptionString$new(
                            "setupLabel",
                            NULL),
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionList$new(
                            "model",
                            NULL,
                            options=list(
                                "richards"),
                            default="richards"),
                        jmvcore::OptionList$new(
                            "errorVarType",
                            NULL,
                            options=list(
                                "none",
                                "power",
                                "exp",
                                "cpower"),
                            default="none"),
                        jmvcore::OptionList$new(
                            "errorCorType",
                            NULL,
                            options=list(
                                "none",
                                "ar1",
                                "car1"),
                            default="none"))))
            private$..duplicateSetup <- jmvcore::OptionAction$new(
                "duplicateSetup",
                duplicateSetup)
            private$..removeSetup <- jmvcore::OptionAction$new(
                "removeSetup",
                removeSetup)
            private$..gofMetrics <- jmvcore::OptionNMXList$new(
                "gofMetrics",
                gofMetrics,
                options=list(
                    "aic",
                    "aicc",
                    "bic",
                    "r2",
                    "r2adj"),
                default=NULL)
            private$..errorMetrics <- jmvcore::OptionNMXList$new(
                "errorMetrics",
                errorMetrics,
                options=list(
                    "rmse",
                    "mae",
                    "medae",
                    "smape",
                    "rrmse"),
                default=NULL)
            private$..iPoints <- jmvcore::OptionBool$new(
                "iPoints",
                iPoints,
                default=FALSE)
            private$..lagPoints <- jmvcore::OptionNMXList$new(
                "lagPoints",
                lagPoints,
                options=list(
                    "ogf0",
                    "paa",
                    "tangent",
                    "threshold"),
                default=NULL)
            private$..thValue <- jmvcore::OptionNumber$new(
                "thValue",
                thValue,
                min=0,
                max=1,
                default=0.01)
            private$..ogfPoints <- jmvcore::OptionNMXList$new(
                "ogfPoints",
                ogfPoints,
                options=list(
                    "ogfMax",
                    "ogfMin"),
                default=NULL)
            private$..accPoints <- jmvcore::OptionNMXList$new(
                "accPoints",
                accPoints,
                options=list(
                    "accMax",
                    "accMin"),
                default=NULL)
            private$..asyPoints <- jmvcore::OptionNMXList$new(
                "asyPoints",
                asyPoints,
                options=list(
                    "ogf3",
                    "pda"),
                default=NULL)
            private$..aucFunction <- jmvcore::OptionNMXList$new(
                "aucFunction",
                aucFunction,
                options=list(
                    "growthFunction",
                    "squaredRate",
                    "gfSquaredRate"),
                default=NULL)
            private$..aucInterval <- jmvcore::OptionBool$new(
                "aucInterval",
                aucInterval,
                default=FALSE)
            private$..aucLower <- jmvcore::OptionNumber$new(
                "aucLower",
                aucLower,
                min=0,
                default=0)
            private$..aucUpper <- jmvcore::OptionNumber$new(
                "aucUpper",
                aucUpper,
                min=0,
                default=0)
            private$..growthPlots <- jmvcore::OptionBool$new(
                "growthPlots",
                growthPlots,
                default=FALSE)
            private$..growthCurveColor <- jmvcore::OptionList$new(
                "growthCurveColor",
                growthCurveColor,
                options=list(
                    "black",
                    "red"),
                default="red")
            private$..growthRightAxis <- jmvcore::OptionBool$new(
                "growthRightAxis",
                growthRightAxis,
                default=FALSE)
            private$..growthRightAxisFunc <- jmvcore::OptionList$new(
                "growthRightAxisFunc",
                growthRightAxisFunc,
                options=list(
                    "ogf",
                    "growthRate",
                    "acceleration",
                    "squaredRate",
                    "gfSquaredRate"),
                default="growthRate")
            private$..growthRightAxisLine <- jmvcore::OptionList$new(
                "growthRightAxisLine",
                growthRightAxisLine,
                options=list(
                    "solid",
                    "dashed"),
                default="dashed")
            private$..growthRightAxisColor <- jmvcore::OptionList$new(
                "growthRightAxisColor",
                growthRightAxisColor,
                options=list(
                    "orange",
                    "blue",
                    "darkblue",
                    "darkgreen",
                    "black"),
                default="black")
            private$..growthNoAxis <- jmvcore::OptionBool$new(
                "growthNoAxis",
                growthNoAxis,
                default=FALSE)
            private$..growthNoAxisFunc <- jmvcore::OptionList$new(
                "growthNoAxisFunc",
                growthNoAxisFunc,
                options=list(
                    "ogf",
                    "growthRate",
                    "acceleration",
                    "squaredRate",
                    "gfSquaredRate"),
                default="ogf")
            private$..growthNoAxisLine <- jmvcore::OptionList$new(
                "growthNoAxisLine",
                growthNoAxisLine,
                options=list(
                    "solid",
                    "dashed"),
                default="solid")
            private$..growthNoAxisColor <- jmvcore::OptionList$new(
                "growthNoAxisColor",
                growthNoAxisColor,
                options=list(
                    "orange",
                    "blue",
                    "darkblue",
                    "darkgreen",
                    "black"),
                default="darkgreen")
            private$..residualPlots <- jmvcore::OptionBool$new(
                "residualPlots",
                residualPlots,
                default=FALSE)
            private$..growthComparisonPlots <- jmvcore::OptionBool$new(
                "growthComparisonPlots",
                growthComparisonPlots,
                default=FALSE)
            private$..comparisonRightFunc <- jmvcore::OptionList$new(
                "comparisonRightFunc",
                comparisonRightFunc,
                options=list(
                    "none",
                    "growthRate",
                    "acceleration",
                    "squaredRate",
                    "gfSquaredRate",
                    "ogf"),
                default="none")
            private$..plotsElements <- jmvcore::OptionNMXList$new(
                "plotsElements",
                plotsElements,
                options=list(
                    "dataPoints",
                    "critPoints"),
                default=NULL)
            private$..timeAxisFactor <- jmvcore::OptionNumber$new(
                "timeAxisFactor",
                timeAxisFactor,
                min=1,
                max=30,
                default=20)

            self$.addOption(private$..deps)
            self$.addOption(private$..time)
            self$.addOption(private$..iid)
            self$.addOption(private$..eqHtmls)
            self$.addOption(private$..parTables)
            self$.addOption(private$..estTables)
            self$.addOption(private$..modeling)
            self$.addOption(private$..duplicateSetup)
            self$.addOption(private$..removeSetup)
            self$.addOption(private$..gofMetrics)
            self$.addOption(private$..errorMetrics)
            self$.addOption(private$..iPoints)
            self$.addOption(private$..lagPoints)
            self$.addOption(private$..thValue)
            self$.addOption(private$..ogfPoints)
            self$.addOption(private$..accPoints)
            self$.addOption(private$..asyPoints)
            self$.addOption(private$..aucFunction)
            self$.addOption(private$..aucInterval)
            self$.addOption(private$..aucLower)
            self$.addOption(private$..aucUpper)
            self$.addOption(private$..growthPlots)
            self$.addOption(private$..growthCurveColor)
            self$.addOption(private$..growthRightAxis)
            self$.addOption(private$..growthRightAxisFunc)
            self$.addOption(private$..growthRightAxisLine)
            self$.addOption(private$..growthRightAxisColor)
            self$.addOption(private$..growthNoAxis)
            self$.addOption(private$..growthNoAxisFunc)
            self$.addOption(private$..growthNoAxisLine)
            self$.addOption(private$..growthNoAxisColor)
            self$.addOption(private$..residualPlots)
            self$.addOption(private$..growthComparisonPlots)
            self$.addOption(private$..comparisonRightFunc)
            self$.addOption(private$..plotsElements)
            self$.addOption(private$..timeAxisFactor)
        }),
    active = list(
        deps = function() private$..deps$value,
        time = function() private$..time$value,
        iid = function() private$..iid$value,
        eqHtmls = function() private$..eqHtmls$value,
        parTables = function() private$..parTables$value,
        estTables = function() private$..estTables$value,
        modeling = function() private$..modeling$value,
        duplicateSetup = function() private$..duplicateSetup$value,
        removeSetup = function() private$..removeSetup$value,
        gofMetrics = function() private$..gofMetrics$value,
        errorMetrics = function() private$..errorMetrics$value,
        iPoints = function() private$..iPoints$value,
        lagPoints = function() private$..lagPoints$value,
        thValue = function() private$..thValue$value,
        ogfPoints = function() private$..ogfPoints$value,
        accPoints = function() private$..accPoints$value,
        asyPoints = function() private$..asyPoints$value,
        aucFunction = function() private$..aucFunction$value,
        aucInterval = function() private$..aucInterval$value,
        aucLower = function() private$..aucLower$value,
        aucUpper = function() private$..aucUpper$value,
        growthPlots = function() private$..growthPlots$value,
        growthCurveColor = function() private$..growthCurveColor$value,
        growthRightAxis = function() private$..growthRightAxis$value,
        growthRightAxisFunc = function() private$..growthRightAxisFunc$value,
        growthRightAxisLine = function() private$..growthRightAxisLine$value,
        growthRightAxisColor = function() private$..growthRightAxisColor$value,
        growthNoAxis = function() private$..growthNoAxis$value,
        growthNoAxisFunc = function() private$..growthNoAxisFunc$value,
        growthNoAxisLine = function() private$..growthNoAxisLine$value,
        growthNoAxisColor = function() private$..growthNoAxisColor$value,
        residualPlots = function() private$..residualPlots$value,
        growthComparisonPlots = function() private$..growthComparisonPlots$value,
        comparisonRightFunc = function() private$..comparisonRightFunc$value,
        plotsElements = function() private$..plotsElements$value,
        timeAxisFactor = function() private$..timeAxisFactor$value),
    private = list(
        ..deps = NA,
        ..time = NA,
        ..iid = NA,
        ..eqHtmls = NA,
        ..parTables = NA,
        ..estTables = NA,
        ..modeling = NA,
        ..duplicateSetup = NA,
        ..removeSetup = NA,
        ..gofMetrics = NA,
        ..errorMetrics = NA,
        ..iPoints = NA,
        ..lagPoints = NA,
        ..thValue = NA,
        ..ogfPoints = NA,
        ..accPoints = NA,
        ..asyPoints = NA,
        ..aucFunction = NA,
        ..aucInterval = NA,
        ..aucLower = NA,
        ..aucUpper = NA,
        ..growthPlots = NA,
        ..growthCurveColor = NA,
        ..growthRightAxis = NA,
        ..growthRightAxisFunc = NA,
        ..growthRightAxisLine = NA,
        ..growthRightAxisColor = NA,
        ..growthNoAxis = NA,
        ..growthNoAxisFunc = NA,
        ..growthNoAxisLine = NA,
        ..growthNoAxisColor = NA,
        ..residualPlots = NA,
        ..growthComparisonPlots = NA,
        ..comparisonRightFunc = NA,
        ..plotsElements = NA,
        ..timeAxisFactor = NA)
)

gcurveResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "gcurveResults",
    inherit = jmvcore::Group,
    active = list(
        eqHtml = function() private$.items[["eqHtml"]],
        parTable = function() private$.items[["parTable"]],
        estTable = function() private$.items[["estTable"]],
        modelEval = function() private$.items[["modelEval"]],
        aucTable = function() private$.items[["aucTable"]],
        critPointsTable = function() private$.items[["critPointsTable"]],
        residualPlot = function() private$.items[["residualPlot"]],
        growthPlot = function() private$.items[["growthPlot"]],
        growthComparisonPlot = function() private$.items[["growthComparisonPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Growth Curve Modeling")
            self$add(jmvcore::Html$new(
                options=options,
                name="eqHtml",
                visible="(eqHtmls)",
                refs=list(
                    "richards")))
            self$add(jmvcore::Table$new(
                options=options,
                name="parTable",
                title="Model Parameters",
                visible="(parTables)",
                clearWith=list(
                    "deps",
                    "time",
                    "model"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="SE", 
                        `type`="number"),
                    list(
                        `name`="Lower", 
                        `type`="number", 
                        `superTitle`="95% Confidence Interval"),
                    list(
                        `name`="Upper", 
                        `type`="number", 
                        `superTitle`="95% Confidence Interval")),
                refs=list(
                    "pgm")))
            self$add(jmvcore::Table$new(
                options=options,
                name="estTable",
                title="Estimation Methods",
                visible="(estTables)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="category", 
                        `title`="Category", 
                        `type`="text"),
                    list(
                        `name`="method", 
                        `title`="Method Used", 
                        `type`="text")),
                refs=list(
                    "pgm",
                    "nlsLM",
                    "nlme")))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    gofTable = function() private$.items[["gofTable"]],
                    emTable = function() private$.items[["emTable"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="modelEval",
                            title="Model Evaluation")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="gofTable",
                            title="Goodness of Fit",
                            visible=FALSE,
                            clearWith=list(
                                "deps",
                                "time",
                                "model"),
                            columns=list(
                                list(
                                    `name`="var", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="AIC", 
                                    `type`="number", 
                                    `visible`="(gofMetrics:aic)"),
                                list(
                                    `name`="AICc", 
                                    `type`="number", 
                                    `visible`="(gofMetrics:aicc)"),
                                list(
                                    `name`="BIC", 
                                    `type`="number", 
                                    `visible`="(gofMetrics:bic)"),
                                list(
                                    `name`="r2", 
                                    `title`="R\u00B2", 
                                    `type`="number", 
                                    `visible`="(gofMetrics:r2)"),
                                list(
                                    `name`="r2adj", 
                                    `title`="Adjusted R\u00B2", 
                                    `type`="number", 
                                    `visible`="(gofMetrics:r2adj)")),
                            refs=list(
                                "pgm")))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="emTable",
                            title="Error Metrics",
                            visible=FALSE,
                            clearWith=list(
                                "deps",
                                "time",
                                "model"),
                            columns=list(
                                list(
                                    `name`="var", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="RMSE", 
                                    `type`="number", 
                                    `visible`="(errorMetrics:rmse)"),
                                list(
                                    `name`="MAE", 
                                    `type`="number", 
                                    `visible`="(errorMetrics:mae)"),
                                list(
                                    `name`="MedAE", 
                                    `type`="number", 
                                    `visible`="(errorMetrics:medae)"),
                                list(
                                    `name`="sMAPE", 
                                    `type`="text", 
                                    `visible`="(errorMetrics:smape)"),
                                list(
                                    `name`="RRMSE", 
                                    `type`="text", 
                                    `visible`="(errorMetrics:rrmse)")),
                            refs=list(
                                "pgm")))}))$new(options=options))
            self$add(jmvcore::Table$new(
                options=options,
                name="aucTable",
                title="Area Under the Curve",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Lower", 
                        `type`="number", 
                        `superTitle`="Time interval"),
                    list(
                        `name`="Upper", 
                        `type`="number", 
                        `superTitle`="Time interval"),
                    list(
                        `name`="gf", 
                        `title`="AUC", 
                        `superTitle`="Growth function", 
                        `type`="number", 
                        `visible`="(aucFunction:growthFunction)"),
                    list(
                        `name`="gfRank", 
                        `title`="Rank", 
                        `superTitle`="Growth function", 
                        `type`="text", 
                        `visible`="(aucFunction:growthFunction)"),
                    list(
                        `name`="sgr", 
                        `title`="AUC", 
                        `superTitle`="Squared rate", 
                        `type`="number", 
                        `visible`="(aucFunction:squaredRate)"),
                    list(
                        `name`="sgrRank", 
                        `title`="Rank", 
                        `superTitle`="Squared rate", 
                        `type`="text", 
                        `visible`="(aucFunction:squaredRate)"),
                    list(
                        `name`="gfSgr", 
                        `title`="AUC", 
                        `superTitle`="Weighted rate\u00B2", 
                        `type`="number", 
                        `visible`="(aucFunction:gfSquaredRate)"),
                    list(
                        `name`="gfSgrRank", 
                        `title`="Rank", 
                        `superTitle`="Weighted rate\u00B2", 
                        `type`="text", 
                        `visible`="(aucFunction:gfSquaredRate)")),
                refs=list(
                    "pgm",
                    "ppfm")))
            self$add(jmvcore::Table$new(
                options=options,
                name="critPointsTable",
                title="Critical points",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Axis", 
                        `type`="text"),
                    list(
                        `name`="F0", 
                        `type`="number", 
                        `visible`="(lagPoints:ogf0)"),
                    list(
                        `name`="PAA", 
                        `type`="number", 
                        `visible`="(lagPoints:paa)"),
                    list(
                        `name`="Tangent", 
                        `type`="number", 
                        `visible`="(lagPoints:tangent)"),
                    list(
                        `name`="Threshold", 
                        `type`="number", 
                        `visible`="(lagPoints:threshold)"),
                    list(
                        `name`="P1", 
                        `type`="number", 
                        `visible`="(accPoints:accMax)"),
                    list(
                        `name`="F1", 
                        `type`="number", 
                        `visible`="(ogfPoints:ogfMax)"),
                    list(
                        `name`="iPoint", 
                        `title`="Inflection (I)", 
                        `type`="number", 
                        `visible`="(iPoints)"),
                    list(
                        `name`="F2", 
                        `type`="number", 
                        `visible`="(ogfPoints:ogfMin)"),
                    list(
                        `name`="P2", 
                        `type`="number", 
                        `visible`="(accPoints:accMin)"),
                    list(
                        `name`="F3", 
                        `type`="number", 
                        `visible`="(asyPoints:ogf3)"),
                    list(
                        `name`="PDA", 
                        `type`="number", 
                        `visible`="(asyPoints:pda)")),
                refs=list(
                    "pgm",
                    "ppfm",
                    "paa",
                    "pda")))
            self$add(jmvcore::Array$new(
                options=options,
                name="residualPlot",
                visible="(residualPlots)",
                title="Residual Analysis",
                items=0,
                template=jmvcore::Image$new(
                    options=options,
                    title="",
                    width=700,
                    height=500,
                    renderFun=".residualPlot",
                    requiresData=TRUE,
                    refs=list(
                        "pgm"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="growthPlot",
                visible="(growthPlots)",
                title="Growth Curves",
                items=0,
                template=jmvcore::Image$new(
                    options=options,
                    title="",
                    width=700,
                    height=500,
                    renderFun=".growthPlot",
                    requiresData=TRUE,
                    refs=list(
                        "pgm"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="growthComparisonPlot",
                visible="(growthComparisonPlots)",
                title="Multiple Growth Curves",
                width=700,
                height=500,
                renderFun=".growthComparisonPlot",
                refs=list(
                    "pgm")))}))

gcurveBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "gcurveBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "PGM",
                name = "gcurve",
                version = c(0,9,0),
                options = options,
                results = gcurveResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Growth Curve Modeling
#'
#' The analysis of Growth Curve Modeling is used to explore the sigmoidal 
#' relationship between a continuous biological dependent variable, 
#' usually weight, height, or another expanding unit, and one continuous 
#' time variable. 
#' 
#' Growth Curve Modeling first fits the chosen model using nonlinear 
#' least squares (NLS) with the Levenberg–Marquardt algorithm, assuming 
#' that the residuals are homoscedastic. If a variance function is 
#' selected, the parameters from the first model are provided as starting 
#' values for Generalized NLS (GNLS) to account for heteroscedasticity 
#' through error weights. 
#' 
#' As growth modeling usually involves repeated measures on the same 
#' individuals, if their identifiers are provided, the parameters from 
#' NLS are provided to a Nonlinear Mixed-Effects function instead of GNLS, 
#' considering both fixed and random effects. At this point, it is also 
#' possible to consider residual heteroscedasticity and autocorrelation.
#' 
#' @param data the data as a data frame
#' @param deps the dependent variables from \code{data}, variables must be
#'   numeric
#' @param time the explanatory variable in \code{data}, must be numeric
#' @param iid the individual identifier variable in \code{data}, must be
#'   categorical
#' @param eqHtmls \code{TRUE} (default) or \code{FALSE}, provide Richards
#'   model equation
#' @param parTables \code{TRUE} (default) or \code{FALSE}, provide estimated
#'   parameters values tables
#' @param estTables \code{TRUE} or \code{FALSE} (default), provide estimated
#'   parameters values  tables
#' @param modeling an array describing the specifications for each model.
#' @param duplicateSetup an action to duplicate the selected model setup with
#'   the same  variable in UI.
#' @param removeSetup an action to remove the selected model setup in UI.
#' @param gofMetrics one or more of \code{'aic'}, \code{'aicc'}, \code{'bic'},
#'   \code{'r2'}, or \code{'r2adj'}
#' @param errorMetrics one or more of \code{'rmse'}, \code{'mae'},
#'   \code{'medae'}, \code{'smape'}, or \code{'rrmse'}
#' @param iPoints \code{TRUE} or \code{FALSE} (default), provide the
#'   inflection point of the growth curve
#' @param lagPoints one or more of \code{'ogf0'}, \code{'paa'},
#'   \code{'tangent'}, or \code{'threshold'}
#' @param thValue a number between 0 and 1 (default: 0.01)
#' @param ogfPoints one or more of \code{'ogfMax'}, or \code{'ogfMin'}
#' @param accPoints one or more of \code{'accMax'}, or \code{'accMin'}
#' @param asyPoints one or more of \code{'ogf3'}, or \code{'pda'}
#' @param aucFunction one or more of \code{'growthFunction'},
#'   \code{'squaredRate'}, or  \code{'gfSquaredRate'}, the function for AUC
#'   calculation
#' @param aucInterval \code{TRUE} or \code{FALSE} (default),
#' @param aucLower a number >= 0 (default: 0), lower interval for AUC
#'   calculation
#' @param aucUpper a number >= 0 (default: 0), upper interval for AUC
#'   calculation
#' @param growthPlots \code{TRUE} or \code{FALSE} (default), provide a plot of
#'   the growth curve
#' @param growthCurveColor \code{'black'}, or \code{'red'} (default), the
#'   model fitted function color  in growthPlots
#' @param growthRightAxis \code{TRUE} or \code{FALSE} (default), provide right
#'   axis to growthPlots
#' @param growthRightAxisFunc \code{'ogf'}, \code{'growthRate'} (default),
#'   \code{'acceleration'}, \code{'squaredRate'},  or \code{'gfSquaredRate'},
#'   the function of right axis in growthPlots
#' @param growthRightAxisLine \code{'solid'}, or \code{'dashed'} (default),
#'   the line type for  growthRightAxisFunc
#' @param growthRightAxisColor \code{'orange'}, 'blue'\code{, 'darkblue'},
#'   'darkgreen'\code{, or  }'black'` (default), the line color for
#'   growthRightAxisFunc
#' @param growthNoAxis \code{TRUE} or \code{FALSE} (default), provide
#'   additional function to  growthPlots
#' @param growthNoAxisFunc \code{'ogf'} (default), \code{'growthRate'},
#'   \code{'acceleration'}, \code{'squaredRate'},  or \code{'gfSquaredRate'},
#'   the additional function of growthPlots
#' @param growthNoAxisLine \code{'solid'} (default), or \code{'dashed'}, the
#'   line type for  growthNoAxisLine
#' @param growthNoAxisColor \code{'orange'}, 'blue'\code{, 'darkblue'},
#'   'darkgreen'\code{, or }'black'`  (default), the line color for
#'   growthRightAxisFunc
#' @param residualPlots \code{TRUE} or \code{FALSE} (default), provide
#'   residual diagnostic plots of  the fitted growth curves
#' @param growthComparisonPlots \code{TRUE} or \code{FALSE} (default), provide
#'   a single plot of all fitted growth curves
#' @param comparisonRightFunc \code{'none'} (default), \code{'acceleration'},
#'   \code{'squaredRate'},  \code{'gfSquaredRate'}, or \code{'ogf'}, the
#'   function of overlaid curves in  growthComparisonPlots
#' @param plotsElements one or more of \code{'dataPoints'}, or
#'   \code{'critPoints'}
#' @param timeAxisFactor a number between 1 and 30 (default: 20),
#'   multiplication factor for  the time vector used in plots and critical
#'   points
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$eqHtml} \tab \tab \tab \tab \tab a HTML block for models equations \cr
#'   \code{results$parTable} \tab \tab \tab \tab \tab a table containing models parameters estimation \cr
#'   \code{results$estTable} \tab \tab \tab \tab \tab a table containing information about estimation methods \cr
#'   \code{results$modelEval$gofTable} \tab \tab \tab \tab \tab a table containing GoF metrics \cr
#'   \code{results$modelEval$emTable} \tab \tab \tab \tab \tab a table containing error metrics \cr
#'   \code{results$aucTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$critPointsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$residualPlot} \tab \tab \tab \tab \tab an array of images \cr
#'   \code{results$growthPlot} \tab \tab \tab \tab \tab an array of images \cr
#'   \code{results$growthComparisonPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$parTable$asDF}
#'
#' \code{as.data.frame(results$parTable)}
#'
#' @export
gcurve <- function(
    data,
    deps,
    time,
    iid = NULL,
    eqHtmls = FALSE,
    parTables = TRUE,
    estTables = FALSE,
    modeling = list(),
    duplicateSetup = FALSE,
    removeSetup = FALSE,
    gofMetrics = NULL,
    errorMetrics = NULL,
    iPoints = FALSE,
    lagPoints = NULL,
    thValue = 0.01,
    ogfPoints = NULL,
    accPoints = NULL,
    asyPoints = NULL,
    aucFunction = NULL,
    aucInterval = FALSE,
    aucLower = 0,
    aucUpper = 0,
    growthPlots = FALSE,
    growthCurveColor = "red",
    growthRightAxis = FALSE,
    growthRightAxisFunc = "growthRate",
    growthRightAxisLine = "dashed",
    growthRightAxisColor = "black",
    growthNoAxis = FALSE,
    growthNoAxisFunc = "ogf",
    growthNoAxisLine = "solid",
    growthNoAxisColor = "darkgreen",
    residualPlots = FALSE,
    growthComparisonPlots = FALSE,
    comparisonRightFunc = "none",
    plotsElements = NULL,
    timeAxisFactor = 20) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("gcurve requires jmvcore to be installed (restart may be required)")

    if ( ! missing(deps)) deps <- jmvcore::resolveQuo(jmvcore::enquo(deps))
    if ( ! missing(time)) time <- jmvcore::resolveQuo(jmvcore::enquo(time))
    if ( ! missing(iid)) iid <- jmvcore::resolveQuo(jmvcore::enquo(iid))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(deps), deps, NULL),
            `if`( ! missing(time), time, NULL),
            `if`( ! missing(iid), iid, NULL))

    for (v in iid) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- gcurveOptions$new(
        deps = deps,
        time = time,
        iid = iid,
        eqHtmls = eqHtmls,
        parTables = parTables,
        estTables = estTables,
        modeling = modeling,
        duplicateSetup = duplicateSetup,
        removeSetup = removeSetup,
        gofMetrics = gofMetrics,
        errorMetrics = errorMetrics,
        iPoints = iPoints,
        lagPoints = lagPoints,
        thValue = thValue,
        ogfPoints = ogfPoints,
        accPoints = accPoints,
        asyPoints = asyPoints,
        aucFunction = aucFunction,
        aucInterval = aucInterval,
        aucLower = aucLower,
        aucUpper = aucUpper,
        growthPlots = growthPlots,
        growthCurveColor = growthCurveColor,
        growthRightAxis = growthRightAxis,
        growthRightAxisFunc = growthRightAxisFunc,
        growthRightAxisLine = growthRightAxisLine,
        growthRightAxisColor = growthRightAxisColor,
        growthNoAxis = growthNoAxis,
        growthNoAxisFunc = growthNoAxisFunc,
        growthNoAxisLine = growthNoAxisLine,
        growthNoAxisColor = growthNoAxisColor,
        residualPlots = residualPlots,
        growthComparisonPlots = growthComparisonPlots,
        comparisonRightFunc = comparisonRightFunc,
        plotsElements = plotsElements,
        timeAxisFactor = timeAxisFactor)

    analysis <- gcurveClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

