
# This file is automatically generated, you probably don't want to edit this

mcurveOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mcurveOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            deps = NULL,
            time = NULL,
            model = "richards",
            pConstraint = "strict",
            agg = "mean",
            trim = FALSE,
            tPerc = 10,
            aic = FALSE,
            aicc = FALSE,
            bic = FALSE,
            r2 = FALSE,
            r2_adj = FALSE,
            rmse = FALSE,
            mae = FALSE,
            medae = FALSE,
            smape = FALSE,
            rrmse = FALSE,
            fTest = FALSE,
            res = 100,
            calcAction = FALSE,
            plotKe = FALSE,
            intInterval = FALSE,
            intL = 0,
            intU = 0, ...) {

            super$initialize(
                package="PGM",
                name="mcurve",
                requiresData=TRUE,
                ...)

            private$..deps <- jmvcore::OptionVariables$new(
                "deps",
                deps,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..time <- jmvcore::OptionVariable$new(
                "time",
                time,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..model <- jmvcore::OptionList$new(
                "model",
                model,
                options=list(
                    "richards"),
                default="richards")
            private$..pConstraint <- jmvcore::OptionList$new(
                "pConstraint",
                pConstraint,
                options=list(
                    "strict",
                    "flex"),
                default="strict")
            private$..agg <- jmvcore::OptionList$new(
                "agg",
                agg,
                options=list(
                    "mean",
                    "median"),
                default="mean")
            private$..trim <- jmvcore::OptionBool$new(
                "trim",
                trim,
                default=FALSE)
            private$..tPerc <- jmvcore::OptionNumber$new(
                "tPerc",
                tPerc,
                min=0,
                max=50,
                default=10)
            private$..aic <- jmvcore::OptionBool$new(
                "aic",
                aic,
                default=FALSE)
            private$..aicc <- jmvcore::OptionBool$new(
                "aicc",
                aicc,
                default=FALSE)
            private$..bic <- jmvcore::OptionBool$new(
                "bic",
                bic,
                default=FALSE)
            private$..r2 <- jmvcore::OptionBool$new(
                "r2",
                r2,
                default=FALSE)
            private$..r2_adj <- jmvcore::OptionBool$new(
                "r2_adj",
                r2_adj,
                default=FALSE)
            private$..rmse <- jmvcore::OptionBool$new(
                "rmse",
                rmse,
                default=FALSE)
            private$..mae <- jmvcore::OptionBool$new(
                "mae",
                mae,
                default=FALSE)
            private$..medae <- jmvcore::OptionBool$new(
                "medae",
                medae,
                default=FALSE)
            private$..smape <- jmvcore::OptionBool$new(
                "smape",
                smape,
                default=FALSE)
            private$..rrmse <- jmvcore::OptionBool$new(
                "rrmse",
                rrmse,
                default=FALSE)
            private$..fTest <- jmvcore::OptionBool$new(
                "fTest",
                fTest,
                default=FALSE)
            private$..res <- jmvcore::OptionNumber$new(
                "res",
                res,
                min=0,
                max=1000,
                default=100)
            private$..calcAction <- jmvcore::OptionBool$new(
                "calcAction",
                calcAction,
                default=FALSE)
            private$..plotKe <- jmvcore::OptionBool$new(
                "plotKe",
                plotKe,
                default=FALSE)
            private$..intInterval <- jmvcore::OptionBool$new(
                "intInterval",
                intInterval,
                default=FALSE)
            private$..intL <- jmvcore::OptionNumber$new(
                "intL",
                intL,
                min=0,
                default=0)
            private$..intU <- jmvcore::OptionNumber$new(
                "intU",
                intU,
                min=0,
                default=0)

            self$.addOption(private$..deps)
            self$.addOption(private$..time)
            self$.addOption(private$..model)
            self$.addOption(private$..pConstraint)
            self$.addOption(private$..agg)
            self$.addOption(private$..trim)
            self$.addOption(private$..tPerc)
            self$.addOption(private$..aic)
            self$.addOption(private$..aicc)
            self$.addOption(private$..bic)
            self$.addOption(private$..r2)
            self$.addOption(private$..r2_adj)
            self$.addOption(private$..rmse)
            self$.addOption(private$..mae)
            self$.addOption(private$..medae)
            self$.addOption(private$..smape)
            self$.addOption(private$..rrmse)
            self$.addOption(private$..fTest)
            self$.addOption(private$..res)
            self$.addOption(private$..calcAction)
            self$.addOption(private$..plotKe)
            self$.addOption(private$..intInterval)
            self$.addOption(private$..intL)
            self$.addOption(private$..intU)
        }),
    active = list(
        deps = function() private$..deps$value,
        time = function() private$..time$value,
        model = function() private$..model$value,
        pConstraint = function() private$..pConstraint$value,
        agg = function() private$..agg$value,
        trim = function() private$..trim$value,
        tPerc = function() private$..tPerc$value,
        aic = function() private$..aic$value,
        aicc = function() private$..aicc$value,
        bic = function() private$..bic$value,
        r2 = function() private$..r2$value,
        r2_adj = function() private$..r2_adj$value,
        rmse = function() private$..rmse$value,
        mae = function() private$..mae$value,
        medae = function() private$..medae$value,
        smape = function() private$..smape$value,
        rrmse = function() private$..rrmse$value,
        fTest = function() private$..fTest$value,
        res = function() private$..res$value,
        calcAction = function() private$..calcAction$value,
        plotKe = function() private$..plotKe$value,
        intInterval = function() private$..intInterval$value,
        intL = function() private$..intL$value,
        intU = function() private$..intU$value),
    private = list(
        ..deps = NA,
        ..time = NA,
        ..model = NA,
        ..pConstraint = NA,
        ..agg = NA,
        ..trim = NA,
        ..tPerc = NA,
        ..aic = NA,
        ..aicc = NA,
        ..bic = NA,
        ..r2 = NA,
        ..r2_adj = NA,
        ..rmse = NA,
        ..mae = NA,
        ..medae = NA,
        ..smape = NA,
        ..rrmse = NA,
        ..fTest = NA,
        ..res = NA,
        ..calcAction = NA,
        ..plotKe = NA,
        ..intInterval = NA,
        ..intL = NA,
        ..intU = NA)
)

mcurveResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mcurveResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        pTable = function() private$.items[["pTable"]],
        fitq = function() private$.items[["fitq"]],
        action = function() private$.items[["action"]],
        mplot = function() private$.items[["mplot"]],
        aplot = function() private$.items[["aplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Growth Curve Comparison")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Results",
                refs=list(
                    "richards")))
            self$add(jmvcore::Table$new(
                options=options,
                name="pTable",
                title="Estimated Parameters",
                rows="(deps)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="A", 
                        `type`="number"),
                    list(
                        `name`="d", 
                        `type`="number"),
                    list(
                        `name`="K", 
                        `type`="number"),
                    list(
                        `name`="Ti", 
                        `type`="number")),
                refs=list(
                    "nlm")))
            self$add(jmvcore::Table$new(
                options=options,
                name="fitq",
                title="Model Evaluation",
                rows="(deps)",
                visible="(aic || aicc || bic || r2 || r2_adj || rmse || mae || medae || smape || rrmse || fTest)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="AIC", 
                        `title`="AIC", 
                        `type`="number", 
                        `superTitle`="Goodness of Fit", 
                        `visible`="(aic)"),
                    list(
                        `name`="AICc", 
                        `title`="AIC\u1D04", 
                        `type`="number", 
                        `superTitle`="Goodness of Fit", 
                        `visible`="(aicc)"),
                    list(
                        `name`="BIC", 
                        `type`="number", 
                        `superTitle`="Goodness of Fit", 
                        `visible`="(bic)"),
                    list(
                        `name`="R2", 
                        `title`="R\u00B2", 
                        `type`="number", 
                        `superTitle`="Goodness of Fit", 
                        `visible`="(r2)"),
                    list(
                        `name`="R2_adj", 
                        `title`="Adjusted R\u00B2", 
                        `type`="number", 
                        `superTitle`="Goodness of Fit", 
                        `visible`="(r2_adj)"),
                    list(
                        `name`="RMSE", 
                        `type`="number", 
                        `superTitle`="Error Metrics", 
                        `visible`="(rmse)"),
                    list(
                        `name`="MAE", 
                        `type`="number", 
                        `superTitle`="Error Metrics", 
                        `visible`="(mae)"),
                    list(
                        `name`="MedAE", 
                        `type`="number", 
                        `superTitle`="Error Metrics", 
                        `visible`="(medae)"),
                    list(
                        `name`="sMAPE", 
                        `type`="text", 
                        `superTitle`="Error Metrics", 
                        `visible`="(smape)"),
                    list(
                        `name`="RRMSE", 
                        `type`="text", 
                        `superTitle`="Error Metrics", 
                        `visible`="(rrmse)"),
                    list(
                        `name`="f", 
                        `title`="F", 
                        `type`="number", 
                        `superTitle`="Global F-test", 
                        `visible`="(fTest)"),
                    list(
                        `name`="fdf1", 
                        `title`="df1", 
                        `type`="integer", 
                        `superTitle`="Global F-test", 
                        `visible`="(fTest)"),
                    list(
                        `name`="fdf2", 
                        `title`="df2", 
                        `type`="integer", 
                        `superTitle`="Global F-test", 
                        `visible`="(fTest)"),
                    list(
                        `name`="fp", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `superTitle`="Global F-test", 
                        `visible`="(fTest)")),
                refs=list(
                    "pgm")))
            self$add(jmvcore::Table$new(
                options=options,
                name="action",
                title="Action",
                rows="(deps)",
                visible="(calcAction)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="Lower", 
                        `type`="number", 
                        `superTitle`="Time interval"),
                    list(
                        `name`="Upper", 
                        `type`="number", 
                        `superTitle`="Time interval"),
                    list(
                        `name`="Action", 
                        `type`="number"),
                    list(
                        `name`="Rank", 
                        `type`="text")),
                refs=list(
                    "pgm",
                    "ppfm")))
            self$add(jmvcore::Image$new(
                options=options,
                name="mplot",
                title="Growth Curves",
                width=700,
                height=500,
                renderFun=".mplot",
                refs=list(
                    "pgm")))
            self$add(jmvcore::Image$new(
                options=options,
                name="aplot",
                title="Kinetic Energy",
                visible="(plotKe)",
                width=700,
                height=500,
                renderFun=".aplot",
                refs=list(
                    "pgm",
                    "ppfm")))}))

mcurveBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mcurveBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "PGM",
                name = "mcurve",
                version = c(0,3,0),
                options = options,
                results = mcurveResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Growth Curve Comparison
#'
#' 
#' @param data .
#' @param deps .
#' @param time .
#' @param model .
#' @param pConstraint .
#' @param agg .
#' @param trim .
#' @param tPerc .
#' @param aic .
#' @param aicc .
#' @param bic .
#' @param r2 .
#' @param r2_adj .
#' @param rmse .
#' @param mae .
#' @param medae .
#' @param smape .
#' @param rrmse .
#' @param fTest .
#' @param res .
#' @param calcAction .
#' @param plotKe .
#' @param intInterval .
#' @param intL .
#' @param intU .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$pTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fitq} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$action} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$aplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$pTable$asDF}
#'
#' \code{as.data.frame(results$pTable)}
#'
#' @export
mcurve <- function(
    data,
    deps,
    time,
    model = "richards",
    pConstraint = "strict",
    agg = "mean",
    trim = FALSE,
    tPerc = 10,
    aic = FALSE,
    aicc = FALSE,
    bic = FALSE,
    r2 = FALSE,
    r2_adj = FALSE,
    rmse = FALSE,
    mae = FALSE,
    medae = FALSE,
    smape = FALSE,
    rrmse = FALSE,
    fTest = FALSE,
    res = 100,
    calcAction = FALSE,
    plotKe = FALSE,
    intInterval = FALSE,
    intL = 0,
    intU = 0) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mcurve requires jmvcore to be installed (restart may be required)")

    if ( ! missing(deps)) deps <- jmvcore::resolveQuo(jmvcore::enquo(deps))
    if ( ! missing(time)) time <- jmvcore::resolveQuo(jmvcore::enquo(time))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(deps), deps, NULL),
            `if`( ! missing(time), time, NULL))


    options <- mcurveOptions$new(
        deps = deps,
        time = time,
        model = model,
        pConstraint = pConstraint,
        agg = agg,
        trim = trim,
        tPerc = tPerc,
        aic = aic,
        aicc = aicc,
        bic = bic,
        r2 = r2,
        r2_adj = r2_adj,
        rmse = rmse,
        mae = mae,
        medae = medae,
        smape = smape,
        rrmse = rrmse,
        fTest = fTest,
        res = res,
        calcAction = calcAction,
        plotKe = plotKe,
        intInterval = intInterval,
        intL = intL,
        intU = intU)

    analysis <- mcurveClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

