
# This file is automatically generated, you probably don't want to edit this

scurveOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scurveOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            time = NULL,
            model = "richards",
            pConstraint = "strict",
            agg = "mean",
            trim = FALSE,
            tPerc = 10,
            aic = FALSE,
            aicc = FALSE,
            bic = FALSE,
            r2 = FALSE,
            r2_adj = FALSE,
            rmse = FALSE,
            mae = FALSE,
            medae = FALSE,
            smape = FALSE,
            rrmse = FALSE,
            fTest = FALSE,
            ogf = FALSE,
            ogf_s = FALSE,
            sndPlot = FALSE,
            keyGrowth = TRUE,
            res = 100,
            fPoints = NULL,
            pPoints = NULL,
            lagEnd = NULL,
            thVal = 0.01,
            asymptote = NULL, ...) {

            super$initialize(
                package="PGM",
                name="scurve",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..time <- jmvcore::OptionVariable$new(
                "time",
                time,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..model <- jmvcore::OptionList$new(
                "model",
                model,
                options=list(
                    "richards"),
                default="richards")
            private$..pConstraint <- jmvcore::OptionList$new(
                "pConstraint",
                pConstraint,
                options=list(
                    "strict",
                    "flex"),
                default="strict")
            private$..agg <- jmvcore::OptionList$new(
                "agg",
                agg,
                options=list(
                    "mean",
                    "median"),
                default="mean")
            private$..trim <- jmvcore::OptionBool$new(
                "trim",
                trim,
                default=FALSE)
            private$..tPerc <- jmvcore::OptionNumber$new(
                "tPerc",
                tPerc,
                min=0,
                max=50,
                default=10)
            private$..aic <- jmvcore::OptionBool$new(
                "aic",
                aic,
                default=FALSE)
            private$..aicc <- jmvcore::OptionBool$new(
                "aicc",
                aicc,
                default=FALSE)
            private$..bic <- jmvcore::OptionBool$new(
                "bic",
                bic,
                default=FALSE)
            private$..r2 <- jmvcore::OptionBool$new(
                "r2",
                r2,
                default=FALSE)
            private$..r2_adj <- jmvcore::OptionBool$new(
                "r2_adj",
                r2_adj,
                default=FALSE)
            private$..rmse <- jmvcore::OptionBool$new(
                "rmse",
                rmse,
                default=FALSE)
            private$..mae <- jmvcore::OptionBool$new(
                "mae",
                mae,
                default=FALSE)
            private$..medae <- jmvcore::OptionBool$new(
                "medae",
                medae,
                default=FALSE)
            private$..smape <- jmvcore::OptionBool$new(
                "smape",
                smape,
                default=FALSE)
            private$..rrmse <- jmvcore::OptionBool$new(
                "rrmse",
                rrmse,
                default=FALSE)
            private$..fTest <- jmvcore::OptionBool$new(
                "fTest",
                fTest,
                default=FALSE)
            private$..ogf <- jmvcore::OptionBool$new(
                "ogf",
                ogf,
                default=FALSE)
            private$..ogf_s <- jmvcore::OptionBool$new(
                "ogf_s",
                ogf_s,
                default=FALSE)
            private$..sndPlot <- jmvcore::OptionBool$new(
                "sndPlot",
                sndPlot,
                default=FALSE)
            private$..keyGrowth <- jmvcore::OptionBool$new(
                "keyGrowth",
                keyGrowth,
                default=TRUE)
            private$..res <- jmvcore::OptionNumber$new(
                "res",
                res,
                min=0,
                max=1000,
                default=100)
            private$..fPoints <- jmvcore::OptionNMXList$new(
                "fPoints",
                fPoints,
                options=list(
                    "ogfMax",
                    "ogfI",
                    "ogfMin"),
                default=NULL)
            private$..pPoints <- jmvcore::OptionNMXList$new(
                "pPoints",
                pPoints,
                options=list(
                    "accMax",
                    "accI",
                    "accMin"),
                default=NULL)
            private$..lagEnd <- jmvcore::OptionNMXList$new(
                "lagEnd",
                lagEnd,
                options=list(
                    "ogf0",
                    "tang",
                    "thres"),
                default=NULL)
            private$..thVal <- jmvcore::OptionNumber$new(
                "thVal",
                thVal,
                min=0,
                max=1,
                default=0.01)
            private$..asymptote <- jmvcore::OptionNMXList$new(
                "asymptote",
                asymptote,
                options=list(
                    "ogf3",
                    "pda"),
                default=NULL)

            self$.addOption(private$..dep)
            self$.addOption(private$..time)
            self$.addOption(private$..model)
            self$.addOption(private$..pConstraint)
            self$.addOption(private$..agg)
            self$.addOption(private$..trim)
            self$.addOption(private$..tPerc)
            self$.addOption(private$..aic)
            self$.addOption(private$..aicc)
            self$.addOption(private$..bic)
            self$.addOption(private$..r2)
            self$.addOption(private$..r2_adj)
            self$.addOption(private$..rmse)
            self$.addOption(private$..mae)
            self$.addOption(private$..medae)
            self$.addOption(private$..smape)
            self$.addOption(private$..rrmse)
            self$.addOption(private$..fTest)
            self$.addOption(private$..ogf)
            self$.addOption(private$..ogf_s)
            self$.addOption(private$..sndPlot)
            self$.addOption(private$..keyGrowth)
            self$.addOption(private$..res)
            self$.addOption(private$..fPoints)
            self$.addOption(private$..pPoints)
            self$.addOption(private$..lagEnd)
            self$.addOption(private$..thVal)
            self$.addOption(private$..asymptote)
        }),
    active = list(
        dep = function() private$..dep$value,
        time = function() private$..time$value,
        model = function() private$..model$value,
        pConstraint = function() private$..pConstraint$value,
        agg = function() private$..agg$value,
        trim = function() private$..trim$value,
        tPerc = function() private$..tPerc$value,
        aic = function() private$..aic$value,
        aicc = function() private$..aicc$value,
        bic = function() private$..bic$value,
        r2 = function() private$..r2$value,
        r2_adj = function() private$..r2_adj$value,
        rmse = function() private$..rmse$value,
        mae = function() private$..mae$value,
        medae = function() private$..medae$value,
        smape = function() private$..smape$value,
        rrmse = function() private$..rrmse$value,
        fTest = function() private$..fTest$value,
        ogf = function() private$..ogf$value,
        ogf_s = function() private$..ogf_s$value,
        sndPlot = function() private$..sndPlot$value,
        keyGrowth = function() private$..keyGrowth$value,
        res = function() private$..res$value,
        fPoints = function() private$..fPoints$value,
        pPoints = function() private$..pPoints$value,
        lagEnd = function() private$..lagEnd$value,
        thVal = function() private$..thVal$value,
        asymptote = function() private$..asymptote$value),
    private = list(
        ..dep = NA,
        ..time = NA,
        ..model = NA,
        ..pConstraint = NA,
        ..agg = NA,
        ..trim = NA,
        ..tPerc = NA,
        ..aic = NA,
        ..aicc = NA,
        ..bic = NA,
        ..r2 = NA,
        ..r2_adj = NA,
        ..rmse = NA,
        ..mae = NA,
        ..medae = NA,
        ..smape = NA,
        ..rrmse = NA,
        ..fTest = NA,
        ..ogf = NA,
        ..ogf_s = NA,
        ..sndPlot = NA,
        ..keyGrowth = NA,
        ..res = NA,
        ..fPoints = NA,
        ..pPoints = NA,
        ..lagEnd = NA,
        ..thVal = NA,
        ..asymptote = NA)
)

scurveResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scurveResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        pTable = function() private$.items[["pTable"]],
        fitq = function() private$.items[["fitq"]],
        fpoints = function() private$.items[["fpoints"]],
        mplot = function() private$.items[["mplot"]],
        dplot = function() private$.items[["dplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Growth Curve Modeling")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="",
                refs=list(
                    "richards")))
            self$add(jmvcore::Table$new(
                options=options,
                name="pTable",
                title="Estimated Parameters",
                rows="(dep)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="A", 
                        `type`="number"),
                    list(
                        `name`="d", 
                        `type`="number"),
                    list(
                        `name`="K", 
                        `type`="number"),
                    list(
                        `name`="Ti", 
                        `type`="number")),
                refs=list(
                    "nlm")))
            self$add(jmvcore::Table$new(
                options=options,
                name="fitq",
                title="Model Evaluation",
                rows="(dep)",
                visible="(aic || aicc || bic || r2 || r2_adj || rmse || mae || medae || smape || rrmse || fTest)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="AIC", 
                        `title`="AIC", 
                        `type`="number", 
                        `superTitle`="Goodness of Fit", 
                        `visible`="(aic)"),
                    list(
                        `name`="AICc", 
                        `title`="AIC\u1D04", 
                        `type`="number", 
                        `superTitle`="Goodness of Fit", 
                        `visible`="(aicc)"),
                    list(
                        `name`="BIC", 
                        `type`="number", 
                        `superTitle`="Goodness of Fit", 
                        `visible`="(bic)"),
                    list(
                        `name`="R2", 
                        `title`="R\u00B2", 
                        `type`="number", 
                        `superTitle`="Goodness of Fit", 
                        `visible`="(r2)"),
                    list(
                        `name`="R2_adj", 
                        `title`="Adjusted R\u00B2", 
                        `type`="number", 
                        `superTitle`="Goodness of Fit", 
                        `visible`="(r2_adj)"),
                    list(
                        `name`="RMSE", 
                        `type`="number", 
                        `superTitle`="Error Metrics", 
                        `visible`="(rmse)"),
                    list(
                        `name`="MAE", 
                        `type`="number", 
                        `superTitle`="Error Metrics", 
                        `visible`="(mae)"),
                    list(
                        `name`="MedAE", 
                        `type`="number", 
                        `superTitle`="Error Metrics", 
                        `visible`="(medae)"),
                    list(
                        `name`="sMAPE", 
                        `type`="text", 
                        `superTitle`="Error Metrics", 
                        `visible`="(smape)"),
                    list(
                        `name`="RRMSE", 
                        `type`="text", 
                        `superTitle`="Error Metrics", 
                        `visible`="(rrmse)"),
                    list(
                        `name`="f", 
                        `title`="F", 
                        `type`="number", 
                        `superTitle`="Global F-test", 
                        `visible`="(fTest)"),
                    list(
                        `name`="fdf1", 
                        `title`="df1", 
                        `type`="integer", 
                        `superTitle`="Global F-test", 
                        `visible`="(fTest)"),
                    list(
                        `name`="fdf2", 
                        `title`="df2", 
                        `type`="integer", 
                        `superTitle`="Global F-test", 
                        `visible`="(fTest)"),
                    list(
                        `name`="fp", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `superTitle`="Global F-test", 
                        `visible`="(fTest)")),
                refs=list(
                    "pgm")))
            self$add(jmvcore::Table$new(
                options=options,
                name="fpoints",
                title="Key Growth Points",
                visible="(lagEnd:tang || lagEnd:thres || lagEnd:ogf0 || fPoints:ogfMax || fPoints:ogfI || fPoints:ogfMin || pPoints:accMax || pPoints:accI || pPoints:accMin || asymptote:ogf3 || asymptote:pda)",
                notes=list(
                    `sig`=NULL),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="OGF0", 
                        `type`="number", 
                        `superTitle`="Exponential Start", 
                        `visible`="(lagEnd:ogf0)"),
                    list(
                        `name`="Tangent", 
                        `type`="number", 
                        `superTitle`="Exponential Start", 
                        `visible`="(lagEnd:tang)"),
                    list(
                        `name`="Threshold", 
                        `type`="number", 
                        `superTitle`="Exponential Start", 
                        `visible`="(lagEnd:thres)"),
                    list(
                        `name`="F1", 
                        `type`="number", 
                        `superTitle`="by Ontogenetic Growth Force", 
                        `visible`="(fPoints:ogfMax)"),
                    list(
                        `name`="Fi", 
                        `type`="number", 
                        `superTitle`="by Ontogenetic Growth Force", 
                        `visible`="(fPoints:ogfI)"),
                    list(
                        `name`="F2", 
                        `type`="number", 
                        `superTitle`="by Ontogenetic Growth Force", 
                        `visible`="(fPoints:ogfMin)"),
                    list(
                        `name`="P1", 
                        `type`="number", 
                        `superTitle`="by Acceleration", 
                        `visible`="(pPoints:accMax)"),
                    list(
                        `name`="Pi", 
                        `type`="number", 
                        `superTitle`="by Acceleration", 
                        `visible`="(pPoints:accI)"),
                    list(
                        `name`="P2", 
                        `type`="number", 
                        `superTitle`="by Acceleration", 
                        `visible`="(pPoints:accMin)"),
                    list(
                        `name`="OGF3", 
                        `type`="number", 
                        `superTitle`="Close to Asymptote", 
                        `visible`="(asymptote:ogf3)"),
                    list(
                        `name`="PDA", 
                        `type`="number", 
                        `superTitle`="Close to Asymptote", 
                        `visible`="(asymptote:pda)")),
                refs=list(
                    "pgm",
                    "ppfm",
                    "pda")))
            self$add(jmvcore::Image$new(
                options=options,
                name="mplot",
                title="Growth Curve",
                width=700,
                height=500,
                renderFun=".mplot",
                refs=list(
                    "pgm")))
            self$add(jmvcore::Image$new(
                options=options,
                name="dplot",
                visible="(sndPlot)",
                title="Growth Rate and Acceleration",
                width=700,
                height=500,
                renderFun=".dplot",
                refs=list(
                    "pgm")))}))

scurveBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scurveBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "PGM",
                name = "scurve",
                version = c(0,3,0),
                options = options,
                results = scurveResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Growth Curve Modeling
#'
#' 
#' @param data .
#' @param dep .
#' @param time .
#' @param model .
#' @param pConstraint .
#' @param agg .
#' @param trim .
#' @param tPerc .
#' @param aic .
#' @param aicc .
#' @param bic .
#' @param r2 .
#' @param r2_adj .
#' @param rmse .
#' @param mae .
#' @param medae .
#' @param smape .
#' @param rrmse .
#' @param fTest .
#' @param ogf .
#' @param ogf_s .
#' @param sndPlot .
#' @param keyGrowth .
#' @param res .
#' @param fPoints .
#' @param pPoints .
#' @param lagEnd .
#' @param thVal .
#' @param asymptote .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$pTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fitq} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fpoints} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$dplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$pTable$asDF}
#'
#' \code{as.data.frame(results$pTable)}
#'
#' @export
scurve <- function(
    data,
    dep,
    time,
    model = "richards",
    pConstraint = "strict",
    agg = "mean",
    trim = FALSE,
    tPerc = 10,
    aic = FALSE,
    aicc = FALSE,
    bic = FALSE,
    r2 = FALSE,
    r2_adj = FALSE,
    rmse = FALSE,
    mae = FALSE,
    medae = FALSE,
    smape = FALSE,
    rrmse = FALSE,
    fTest = FALSE,
    ogf = FALSE,
    ogf_s = FALSE,
    sndPlot = FALSE,
    keyGrowth = TRUE,
    res = 100,
    fPoints = NULL,
    pPoints = NULL,
    lagEnd = NULL,
    thVal = 0.01,
    asymptote = NULL) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("scurve requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(time)) time <- jmvcore::resolveQuo(jmvcore::enquo(time))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(time), time, NULL))


    options <- scurveOptions$new(
        dep = dep,
        time = time,
        model = model,
        pConstraint = pConstraint,
        agg = agg,
        trim = trim,
        tPerc = tPerc,
        aic = aic,
        aicc = aicc,
        bic = bic,
        r2 = r2,
        r2_adj = r2_adj,
        rmse = rmse,
        mae = mae,
        medae = medae,
        smape = smape,
        rrmse = rrmse,
        fTest = fTest,
        ogf = ogf,
        ogf_s = ogf_s,
        sndPlot = sndPlot,
        keyGrowth = keyGrowth,
        res = res,
        fPoints = fPoints,
        pPoints = pPoints,
        lagEnd = lagEnd,
        thVal = thVal,
        asymptote = asymptote)

    analysis <- scurveClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

