
# This file is automatically generated, you probably don't want to edit this

scurveOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scurveOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            time = NULL,
            model = "richards",
            pConstraint = "strict",
            agg = "mean",
            trim = FALSE,
            tPerc = 10,
            aic = FALSE,
            aicc = FALSE,
            bic = FALSE,
            r2 = FALSE,
            fTest = FALSE,
            ogf = FALSE,
            ogf3 = FALSE,
            sndPlot = FALSE,
            res = 100,
            fPoints = FALSE,
            pPoints = FALSE, ...) {

            super$initialize(
                package="PGM",
                name="scurve",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..time <- jmvcore::OptionVariable$new(
                "time",
                time,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..model <- jmvcore::OptionList$new(
                "model",
                model,
                options=list(
                    "richards"),
                default="richards")
            private$..pConstraint <- jmvcore::OptionList$new(
                "pConstraint",
                pConstraint,
                options=list(
                    "strict",
                    "flex"),
                default="strict")
            private$..agg <- jmvcore::OptionList$new(
                "agg",
                agg,
                options=list(
                    "mean",
                    "median"),
                default="mean")
            private$..trim <- jmvcore::OptionBool$new(
                "trim",
                trim,
                default=FALSE)
            private$..tPerc <- jmvcore::OptionNumber$new(
                "tPerc",
                tPerc,
                min=0,
                max=50,
                default=10)
            private$..aic <- jmvcore::OptionBool$new(
                "aic",
                aic,
                default=FALSE)
            private$..aicc <- jmvcore::OptionBool$new(
                "aicc",
                aicc,
                default=FALSE)
            private$..bic <- jmvcore::OptionBool$new(
                "bic",
                bic,
                default=FALSE)
            private$..r2 <- jmvcore::OptionBool$new(
                "r2",
                r2,
                default=FALSE)
            private$..fTest <- jmvcore::OptionBool$new(
                "fTest",
                fTest,
                default=FALSE)
            private$..ogf <- jmvcore::OptionBool$new(
                "ogf",
                ogf,
                default=FALSE)
            private$..ogf3 <- jmvcore::OptionBool$new(
                "ogf3",
                ogf3,
                default=FALSE)
            private$..sndPlot <- jmvcore::OptionBool$new(
                "sndPlot",
                sndPlot,
                default=FALSE)
            private$..res <- jmvcore::OptionNumber$new(
                "res",
                res,
                min=0,
                max=1000,
                default=100)
            private$..fPoints <- jmvcore::OptionBool$new(
                "fPoints",
                fPoints,
                default=FALSE)
            private$..pPoints <- jmvcore::OptionBool$new(
                "pPoints",
                pPoints,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..time)
            self$.addOption(private$..model)
            self$.addOption(private$..pConstraint)
            self$.addOption(private$..agg)
            self$.addOption(private$..trim)
            self$.addOption(private$..tPerc)
            self$.addOption(private$..aic)
            self$.addOption(private$..aicc)
            self$.addOption(private$..bic)
            self$.addOption(private$..r2)
            self$.addOption(private$..fTest)
            self$.addOption(private$..ogf)
            self$.addOption(private$..ogf3)
            self$.addOption(private$..sndPlot)
            self$.addOption(private$..res)
            self$.addOption(private$..fPoints)
            self$.addOption(private$..pPoints)
        }),
    active = list(
        dep = function() private$..dep$value,
        time = function() private$..time$value,
        model = function() private$..model$value,
        pConstraint = function() private$..pConstraint$value,
        agg = function() private$..agg$value,
        trim = function() private$..trim$value,
        tPerc = function() private$..tPerc$value,
        aic = function() private$..aic$value,
        aicc = function() private$..aicc$value,
        bic = function() private$..bic$value,
        r2 = function() private$..r2$value,
        fTest = function() private$..fTest$value,
        ogf = function() private$..ogf$value,
        ogf3 = function() private$..ogf3$value,
        sndPlot = function() private$..sndPlot$value,
        res = function() private$..res$value,
        fPoints = function() private$..fPoints$value,
        pPoints = function() private$..pPoints$value),
    private = list(
        ..dep = NA,
        ..time = NA,
        ..model = NA,
        ..pConstraint = NA,
        ..agg = NA,
        ..trim = NA,
        ..tPerc = NA,
        ..aic = NA,
        ..aicc = NA,
        ..bic = NA,
        ..r2 = NA,
        ..fTest = NA,
        ..ogf = NA,
        ..ogf3 = NA,
        ..sndPlot = NA,
        ..res = NA,
        ..fPoints = NA,
        ..pPoints = NA)
)

scurveResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scurveResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        pTable = function() private$.items[["pTable"]],
        fitq = function() private$.items[["fitq"]],
        fpoints = function() private$.items[["fpoints"]],
        mplot = function() private$.items[["mplot"]],
        dplot = function() private$.items[["dplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Growth Curve Modeling")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="",
                refs=list(
                    "richards")))
            self$add(jmvcore::Table$new(
                options=options,
                name="pTable",
                title="Estimated Parameters",
                rows="(dep)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="A", 
                        `type`="number"),
                    list(
                        `name`="d", 
                        `type`="number"),
                    list(
                        `name`="K", 
                        `type`="number"),
                    list(
                        `name`="Ti", 
                        `type`="number")),
                refs=list(
                    "nlm")))
            self$add(jmvcore::Table$new(
                options=options,
                name="fitq",
                title="Goodness-of-fit",
                rows="(dep)",
                visible="(aic || aicc || bic || r2 || fTest)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="AIC", 
                        `title`="AIC", 
                        `type`="number", 
                        `visible`="(aic)"),
                    list(
                        `name`="AICc", 
                        `title`="AIC\u1D04", 
                        `type`="number", 
                        `visible`="(aicc)"),
                    list(
                        `name`="BIC", 
                        `type`="number", 
                        `visible`="(bic)"),
                    list(
                        `name`="R2", 
                        `title`="R\u00B2", 
                        `type`="number", 
                        `visible`="(r2)"),
                    list(
                        `name`="f", 
                        `title`="F", 
                        `type`="number", 
                        `superTitle`="Global F-test", 
                        `visible`="(fTest)"),
                    list(
                        `name`="fdf1", 
                        `title`="df1", 
                        `type`="integer", 
                        `superTitle`="Global F-test", 
                        `visible`="(fTest)"),
                    list(
                        `name`="fdf2", 
                        `title`="df2", 
                        `type`="integer", 
                        `superTitle`="Global F-test", 
                        `visible`="(fTest)"),
                    list(
                        `name`="fp", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `superTitle`="Global F-test", 
                        `visible`="(fTest)")),
                refs=list(
                    "pgm")))
            self$add(jmvcore::Table$new(
                options=options,
                name="fpoints",
                title="Key Growth Points",
                visible="(fPoints || pPoints)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="F0", 
                        `type`="number", 
                        `superTitle`="by Ontogenetic Growth Force", 
                        `visible`="(fPoints)"),
                    list(
                        `name`="F1", 
                        `type`="number", 
                        `superTitle`="by Ontogenetic Growth Force", 
                        `visible`="(fPoints)"),
                    list(
                        `name`="Fi", 
                        `type`="number", 
                        `superTitle`="by Ontogenetic Growth Force", 
                        `visible`="(fPoints)"),
                    list(
                        `name`="F2", 
                        `type`="number", 
                        `superTitle`="by Ontogenetic Growth Force", 
                        `visible`="(fPoints)"),
                    list(
                        `name`="F3", 
                        `type`="number", 
                        `superTitle`="by Ontogenetic Growth Force", 
                        `visible`="(fPoints)"),
                    list(
                        `name`="P1", 
                        `type`="number", 
                        `superTitle`="by Growth Rate and Acceleration", 
                        `visible`="(pPoints)"),
                    list(
                        `name`="Pi", 
                        `type`="number", 
                        `superTitle`="by Growth Rate and Acceleration", 
                        `visible`="(pPoints)"),
                    list(
                        `name`="P2", 
                        `type`="number", 
                        `superTitle`="by Growth Rate and Acceleration", 
                        `visible`="(pPoints)")),
                refs=list(
                    "pgm")))
            self$add(jmvcore::Image$new(
                options=options,
                name="mplot",
                title="Growth Curve",
                width=700,
                height=500,
                renderFun=".mplot",
                refs=list(
                    "pgm")))
            self$add(jmvcore::Image$new(
                options=options,
                name="dplot",
                visible="(sndPlot)",
                title="Growth Rate and Acceleration",
                width=700,
                height=500,
                renderFun=".dplot",
                refs=list(
                    "pgm")))}))

scurveBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scurveBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "PGM",
                name = "scurve",
                version = c(0,2,1),
                options = options,
                results = scurveResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Growth Curve Modeling
#'
#' 
#' @param data .
#' @param dep .
#' @param time .
#' @param model .
#' @param pConstraint .
#' @param agg .
#' @param trim .
#' @param tPerc .
#' @param aic .
#' @param aicc .
#' @param bic .
#' @param r2 .
#' @param fTest .
#' @param ogf .
#' @param ogf3 .
#' @param sndPlot .
#' @param res .
#' @param fPoints .
#' @param pPoints .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$pTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fitq} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fpoints} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$dplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$pTable$asDF}
#'
#' \code{as.data.frame(results$pTable)}
#'
#' @export
scurve <- function(
    data,
    dep,
    time,
    model = "richards",
    pConstraint = "strict",
    agg = "mean",
    trim = FALSE,
    tPerc = 10,
    aic = FALSE,
    aicc = FALSE,
    bic = FALSE,
    r2 = FALSE,
    fTest = FALSE,
    ogf = FALSE,
    ogf3 = FALSE,
    sndPlot = FALSE,
    res = 100,
    fPoints = FALSE,
    pPoints = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("scurve requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(time)) time <- jmvcore::resolveQuo(jmvcore::enquo(time))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(time), time, NULL))


    options <- scurveOptions$new(
        dep = dep,
        time = time,
        model = model,
        pConstraint = pConstraint,
        agg = agg,
        trim = trim,
        tPerc = tPerc,
        aic = aic,
        aicc = aicc,
        bic = bic,
        r2 = r2,
        fTest = fTest,
        ogf = ogf,
        ogf3 = ogf3,
        sndPlot = sndPlot,
        res = res,
        fPoints = fPoints,
        pPoints = pPoints)

    analysis <- scurveClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

